# Generated by Django 3.2.2 on 2021-05-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_saida', models.DateTimeField(auto_now_add=True, verbose_name='Saida')),
                ('hora_chegada', models.DateTimeField(auto_now=True, verbose_name='Chegada')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidade_Destino', to='empresa.unidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidade_Origem', to='empresa.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidade', to='empresa.unidade')),
            ],
        ),
    ]
